apiVersion: v1
kind: Namespace
metadata:
  name: does-2
  namespace: does-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: does-2
  namespace: does-2
  labels:
    app: does-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: does-2
  template:
    metadata:
      labels:
        app: does-2
    spec:
      containers:
        - name: does-2
          image: 955116512041.dkr.ecr.us-east-2.amazonaws.com/ld-demo-does-2-myappimage-rgtzoogeov6f:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: does-2
  name: does-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: does-2
  type: LoadBalancer